org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
org.gradle.parallel=true

# Mod properties
mod_id=example
mod_version=1.0.0
mod_name=Example Mod
mod_description=Start to make your fantastic Minecraft Mod!
mod_authors=Me!
mod_credits=Some cool guy here
mod_license=CC BY 4.0
mod_homepage=https://github.com/qyl27/architectury-loom-template
mod_sources=https://github.com/qyl27/architectury-loom-template
mod_issues_page=https://github.com/qyl27/architectury-loom-template/issues
maven_group=com.example
archive_base_name=example-mod
enabled_platforms=fabric,neoforge

# Minecraft
minecraft_version=1.21.1
parchment_minecraft_version=1.21.1
parchment_version=2024.11.17

# Loaders version
neoforge_loader_version=4
neoforge_version=21.1.215
fabric_loader_version=0.17.3
fabric_api_version=0.116.7+1.21.1

# Dependencies version
fabric_mod_menu_version=11.0.3
# Template: Uncomment line below if you'd like to use Architecury API.
#architectury_api_version=13.0.8

# Version range used in mod metadata
neoforge_minecraft_version_range=[1.21,)
neoforge_loader_version_range=[4,)
neoforge_version_range=[21.1,)

fabric_minecraft_version_range=>=1.21
fabric_loader_version_range=>=0.17
fabric_api_version_range=*
